#ddev-generated
# Simple template to demonstrate addon-template
services:
  backstop:
    container_name: ddev-${DDEV_SITENAME}-backstop
    image: backstopjs/backstopjs:6.3.23
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
