#!/bin/sh

## Description: Run backstop visual regression tests
## Usage: backstop [flags] [args]
## Example: ddev backstop test --target=local --list=alls

cd ../web && backstop --config=/src/backstop-local.json "$@"
